build_from:
  amd64: ghcr.io/home-assistant/amd64-base:3.20
  aarch64: ghcr.io/home-assistant/aarch64-base:3.20
  armv7: ghcr.io/home-assistant/armv7-base:3.20
  i386: ghcr.io/home-assistant/i386-base:3.20
labels:
  org.opencontainers.image.title: "Spotify Playlist Builder"
  org.opencontainers.image.description: "Generate/update Spotify playlists via HA automation"
  org.opencontainers.image.source: "https://github.com/rolex86/ha-addons"
