from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile

from .models import Station
from .utils import preferred_stream_url


def build_station_bundle(
    stations: list[Station],
    target: Path,
    logos_dir: Path,
) -> tuple[Path, Path]:
    target.parent.mkdir(parents=True, exist_ok=True)
    manifest_path = target.with_suffix(".json")
    export_stations = [_export_station_view(station) for station in stations]
    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "format": "ha-moode-radios-v1",
        "stations": [station.model_dump(mode="json") for station in export_stations],
    }
    manifest_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    with ZipFile(target, "w", compression=ZIP_DEFLATED) as archive:
        archive.writestr("stations.json", json.dumps(payload, indent=2))
        for station in export_stations:
            archive.writestr(
                f"radio/{station.file_basename}.pls",
                build_pls(station),
            )
        if logos_dir.exists():
            for path in sorted(logos_dir.glob("*.jpg")):
                archive.write(path, arcname=f"logos/{path.name}")
        archive.writestr(
            "README.txt",
            (
                "Generated by the HA moOde Radios add-on.\n"
                "Bundle contains canonical stations.json, .pls files and generated logos.\n"
            ),
        )
    return target, manifest_path


def _export_station_view(station: Station) -> Station:
    preferred_url = preferred_stream_url(station.stream_url_raw, station.stream_url_resolved)
    return station.model_copy(
        update={
            "stream_url_resolved": preferred_url or station.stream_url_resolved,
        }
    )


def build_pls(station: Station) -> str:
    stream_url = preferred_stream_url(station.stream_url_raw, station.stream_url_resolved)
    return (
        "[playlist]\n"
        "NumberOfEntries=1\n"
        f"File1={stream_url}\n"
        f"Title1={station.display_name}\n"
        "Length1=-1\n"
        "Version=2\n"
        "; managed-by=ha-moode-radios-addon\n"
    )
